web:
  build: .
  command: composer update
  links:
    - db
  ports:
    - "8000:80"
  volumes:
    - ./:/var/www/html/php/Silex

db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp