web:
  build: .
  #command: composer update
  ports:
    - "8000:80"
  volumes:
    - ./:/var/www/html/php/Silex

  myapi:
      build: ./../api
      command: node_modules/.bin/nodemon --exec npm start
      environment:
          PORT: 4000
      ports:
          - "4000:4000"
      volumes:
          - ./api:/home/api