version: '2'
services:
  app:
    build: .
    container_name: silex-app
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - ./:/var/www/html/php/Silex
      - /var/www/html/php/Silex/vendor
  redis:
    image: redis
    container_name: silex-redis

  # MySQL (5.7)
  db:
    image: mysql:5.7
    ports:
      - "3310:3306"
    container_name: silex-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=silexphp
      - MYSQL_DATABASE=silexphp
      - MYSQL_USER=silexphp
      - MYSQL_PASSWORD=silexphp