version: '2'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./:/var/www/html/php/Silex
  redis:
    image: redis